### ISSUE TITLE
Snakefile syntax error

### ISSUE THREAD

**Issue by WJH58** [BodenmillerGroup/ImcSegmentationSnakemake#4]
Hi, thank you for providing this pipeline! 
When I run ```snakemake``` command, a syntax error occured: 
```
SyntaxError in line 391 of /cluster/home/xxx/ImcSegmentationPip/workflow/Snakefile:
Unexpected keyword container in rule definition (Snakefile, line 391)
```
I am sorry if this question is too basic, but why did this happen? I couldn't even try ```snakemake download_example_data --use-singularity --cores 32``` because of this syntax error.

Thank you in advance for your help!

**Comment by nilseling** [comment]
Hi @WJH58,
unless @votti disagrees, this repository is not actively maintained anymore. I would recommend having a look at [steinbock](https://github.com/BodenmillerGroup/steinbock) for a dockerized version of the IMC segmentation pipeline. Please let me know if this is sufficient for you.

**Comment by WJH58** [comment]
OK, that helps and thank you!
